spring.mail.host=smtp.office365.com
spring.mail.port=587

spring.mail.username=norielfernando.gecolea@lpulaguna.edu.ph
spring.mail.password=Nors10232001....

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.debug=true


spring.datasource.url=jdbc:postgresql://localhost:5432/lpu_reservation
spring.datasource.username=postgres
spring.datasource.password=Lpu-1234

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.main.web-application-type=servlet
spring.mvc.enabled=true