services:

  postgres:
    image: postgres:17
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
      - ./data/postgres/init:/docker-entrypoint-initdb.d

 
  tomcat:
    image: tomcat:11.0.22-jdk21
    container_name: tomcat_server
    ports:
      - "8080:8080"
    volumes:
      # Mount your local WAR files to deploy them automatically
      - ./data/tomcat/webapps:/usr/local/tomcat/webapps
      # Persistent logs on your host machine
      - ./data/tomcat/logs:/usr/local/tomcat/logs

  angular:
    image: node:24-alpine
    container_name: angular-app

    working_dir: /app

    volumes:
      - ./frontend/frontend:/app
      - /app/node_modules

    ports:
      - "4200:4200"

    environment:
      BACKEND_URL: http://tomcat:8080

    command: sh -c "npm install && npx ng serve --host 0.0.0.0 --port 4200 --proxy-config proxy.conf.js"

    stdin_open: true
    tty: true

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./data/web/templates:/etc/nginx/templates
    environment:
      NGINX_PORT: 80
      SERVER_NAME: localhost
      UPSTREAM_HOST: angular
      UPSTREAM_PORT: 4200
      TOMCAT_HOST: tomcat
      TOMCAT_PORT: 8080
    depends_on:
      - angular
      - tomcat

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped

    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    
    volumes:
      - ./data/cloudflared:/etc/cloudflared

    depends_on:
      - web
